# Generated by Django 3.2 on 2021-04-28 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('taxes', models.FloatField()),
                ('paid', models.FloatField()),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gov_id', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('idpayment', models.IntegerField(primary_key=True, serialize=False)),
                ('types', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('txn_id', models.IntegerField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=45)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
