# Generated by Django 3.2 on 2021-04-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210428_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='cost_of_shipping',
        ),
    ]
